from enum import Enum


class ActivityActivityType(str, Enum):
    ACCESS_BLOCKED = "ACCESS_BLOCKED"
    ACCESS_UNBLOCKED = "ACCESS_UNBLOCKED"
    COMMENTS = "COMMENTS"
    CUSTOMER_ACCESS_UNBLOCKED = "CUSTOMER_ACCESS_UNBLOCKED"
    CUSTOMER_BLOCKED = "CUSTOMER_BLOCKED"
    CUSTOMER_UNBLOCKED = "CUSTOMER_UNBLOCKED"
    EMAIL = "EMAIL"
    LETTER = "LETTER"
    PHONE = "PHONE"
    SYSTEM = "SYSTEM"
    SYSTEM_API = "SYSTEM_API"
    SYSTEM_CUSTOMER = "SYSTEM_CUSTOMER"
    SYSTEM_EMAIL = "SYSTEM_EMAIL"
    SYSTEM_SUPPORTER = "SYSTEM_SUPPORTER"

    def __str__(self) -> str:
        return str(self.value)
