from enum import Enum


class AnalyticsTransactionsPaymentAction(str, Enum):
    AMAZON_EXECUTE_PAYMENT = "AMAZON_EXECUTE_PAYMENT"
    AMAZON_EXECUTE_REFUND = "AMAZON_EXECUTE_REFUND"
    AMAZON_FINISH_CHECKOUT_SESSION = "AMAZON_FINISH_CHECKOUT_SESSION"
    AMAZON_PAY_INITIALIZATION = "AMAZON_PAY_INITIALIZATION"
    BANK_FEES = "BANK_FEES"
    CREDIT_CARD_AUTHORIZATION = "CREDIT_CARD_AUTHORIZATION"
    CREDIT_CARD_CHARGEBACK = "CREDIT_CARD_CHARGEBACK"
    CREDIT_CARD_INITIALIZATION = "CREDIT_CARD_INITIALIZATION"
    CREDIT_CARD_PAYMENT = "CREDIT_CARD_PAYMENT"
    CREDIT_CARD_PRE_AUTHORIZATION = "CREDIT_CARD_PRE_AUTHORIZATION"
    CREDIT_CARD_REFUND = "CREDIT_CARD_REFUND"
    CREDIT_CARD_VERIFICATION = "CREDIT_CARD_VERIFICATION"
    IDEAL_DATA = "IDEAL_DATA"
    IDEAL_INITIALIZATION = "IDEAL_INITIALIZATION"
    PAYPAL_PAYMENT = "PAYPAL_PAYMENT"
    PAYPAL_PAYMENT_FAILED = "PAYPAL_PAYMENT_FAILED"
    PAYPAL_PAYOUT = "PAYPAL_PAYOUT"
    PAYPAL_REFERENCE_TRANSACTION = "PAYPAL_REFERENCE_TRANSACTION"
    PAYPAL_REFUND = "PAYPAL_REFUND"
    SEPA_DEBIT = "SEPA_DEBIT"
    SEPA_DEBIT_RETURN = "SEPA_DEBIT_RETURN"
    SEPA_MANDATE_CREATION = "SEPA_MANDATE_CREATION"
    SEPA_VOID = "SEPA_VOID"
    SOFORT_PAYMENT = "SOFORT_PAYMENT"
    SOFORT_REFUND = "SOFORT_REFUND"

    def __str__(self) -> str:
        return str(self.value)
