from enum import Enum


class CallbackLogEntryEntityType(str, Enum):
    APP_STORE_ORDER = "APP_STORE_ORDER"
    APP_STORE_SUBSCRIPTION = "APP_STORE_SUBSCRIPTION"
    CUSTOMER = "CUSTOMER"
    EVENT_LIST_DATE = "EVENT_LIST_DATE"
    INVOICE = "INVOICE"
    INVOICE_CANCELLATION = "INVOICE_CANCELLATION"
    INVOICE_CORRECTION = "INVOICE_CORRECTION"
    ORDER = "ORDER"
    PURCHASED_ADDON = "PURCHASED_ADDON"
    SUBSCRIPTION = "SUBSCRIPTION"
    TRANSACTION = "TRANSACTION"

    def __str__(self) -> str:
        return str(self.value)
