from enum import Enum


class ProcessSettingsSsoName(str, Enum):
    LOGIN_OPTIONAL = "LOGIN_OPTIONAL"
    LOGIN_REQUIRED = "LOGIN_REQUIRED"
    NONE = "NONE"
    OPTIONAL = "OPTIONAL"
    REGISTRATION_OPTIONAL = "REGISTRATION_OPTIONAL"
    REGISTRATION_OPTIONAL_LOGIN_REQUIRED = "REGISTRATION_OPTIONAL_LOGIN_REQUIRED"
    REGISTRATION_REQUIRED = "REGISTRATION_REQUIRED"
    REGISTRATION_REQUIRED_LOGIN_OPTIONAL = "REGISTRATION_REQUIRED_LOGIN_OPTIONAL"
    REQUIRED = "REQUIRED"

    def __str__(self) -> str:
        return str(self.value)
