from enum import Enum


class SearchCallbackLogsEntityType(str, Enum):
    APP_STORE_ORDER = "APP_STORE_ORDER"
    APP_STORE_SUBSCRIPTION = "APP_STORE_SUBSCRIPTION"
    CALLBACK_RENEWAL = "CALLBACK_RENEWAL"
    CROSS_CLIENT_ORDER = "CROSS_CLIENT_ORDER"
    CUSTOMER = "CUSTOMER"
    CUSTOMER_GDPR = "CUSTOMER_GDPR"
    CUSTOMER_OPT_IN = "CUSTOMER_OPT_IN"
    DOO_EVENT_ACCESS = "DOO_EVENT_ACCESS"
    FAILED_PAYMENT = "FAILED_PAYMENT"
    INVOICE = "INVOICE"
    INVOICE_CANCELLATION = "INVOICE_CANCELLATION"
    INVOICE_CORRECTION = "INVOICE_CORRECTION"
    ORDER = "ORDER"
    PURCHASED_ADDON = "PURCHASED_ADDON"
    SUBSCRIPTION = "SUBSCRIPTION"
    TRANSACTION = "TRANSACTION"
    VOUCHER_CAMPAIGN = "VOUCHER_CAMPAIGN"
    VOUCHER_CHANNEL = "VOUCHER_CHANNEL"

    def __str__(self) -> str:
        return str(self.value)
