from enum import Enum


class SearchMailLogsMailTemplateType(str, Enum):
    CHANGE_EMAIL = "CHANGE_EMAIL"
    CROSS_SELLING = "CROSS_SELLING"
    INVOICE = "INVOICE"
    ORDER = "ORDER"
    ORDER_ITEM_VOUCHER = "ORDER_ITEM_VOUCHER"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    PAYMENT_METHOD_CHANGED = "PAYMENT_METHOD_CHANGED"
    RECURRING_PAYMENT_FAILED = "RECURRING_PAYMENT_FAILED"
    RECURRING_PAYMENT_TRY_FAILED = "RECURRING_PAYMENT_TRY_FAILED"
    REGISTRATION_ALREADY_FINISHED = "REGISTRATION_ALREADY_FINISHED"
    REGISTRATION_COMPLETION = "REGISTRATION_COMPLETION"
    REGISTRATION_FINISHED = "REGISTRATION_FINISHED"
    RESET_PASSWORD = "RESET_PASSWORD"
    RESET_PASSWORD_FINISHED = "RESET_PASSWORD_FINISHED"
    SUBSCRIPTION_CANCELED = "SUBSCRIPTION_CANCELED"
    SUBSCRIPTION_CANCELLATION_TERMINATION = "SUBSCRIPTION_CANCELLATION_TERMINATION"
    SUBSCRIPTION_DELIVERY_PAUSED = "SUBSCRIPTION_DELIVERY_PAUSED"
    SUBSCRIPTION_DELIVERY_PAUSED_CANCELED = "SUBSCRIPTION_DELIVERY_PAUSED_CANCELED"
    SUBSCRIPTION_PAUSED = "SUBSCRIPTION_PAUSED"
    SUBSCRIPTION_PAUSED_CANCELED = "SUBSCRIPTION_PAUSED_CANCELED"
    SUBSCRIPTION_RELATION_RULE = "SUBSCRIPTION_RELATION_RULE"
    WELCOME_MAIL = "WELCOME_MAIL"

    def __str__(self) -> str:
        return str(self.value)
