from enum import Enum


class SubscriptionIvwRecordIvwType(str, Enum):
    ABONNEMENT = "ABONNEMENT"
    BORDEXEMPLAR = "BORDEXEMPLAR"
    EINZELVERKAUF = "EINZELVERKAUF"
    FREISTUECK = "FREISTUECK"
    KOLLEGENABONNEMENT = "KOLLEGENABONNEMENT"
    KOPPELABONNEMENT = "KOPPELABONNEMENT"
    LESEZIRKEL = "LESEZIRKEL"
    MITGLIEDERSTUECK = "MITGLIEDERSTUECK"
    PERSONALSTUECK = "PERSONALSTUECK"
    REMITTEND = "REMITTEND"
    REST_EXEMPLAR = "REST_EXEMPLAR"
    SONSTIGER_VERKAUF = "SONSTIGER_VERKAUF"
    STUDENTENABONNEMENT = "STUDENTENABONNEMENT"

    def __str__(self) -> str:
        return str(self.value)
