from enum import Enum


class TaxType(str, Enum):
    ADVERTISEMENT = "ADVERTISEMENT"
    BOOK = "BOOK"
    BUNDLE = "BUNDLE"
    DIGITALNEWSPAPER = "DIGITALNEWSPAPER"
    DIGITALOFFER = "DIGITALOFFER"
    DIGITALPRODUCT = "DIGITALPRODUCT"
    DONATION = "DONATION"
    DOWNLOAD = "DOWNLOAD"
    EBOOK = "EBOOK"
    EVENT = "EVENT"
    FEE = "FEE"
    MAGAZINE = "MAGAZINE"
    MEMBERSHIP = "MEMBERSHIP"
    MUSIC = "MUSIC"
    NEWSPAPER = "NEWSPAPER"
    PHYSICALPRODUCT = "PHYSICALPRODUCT"
    SHIPPINGCOSTS = "SHIPPINGCOSTS"
    VIDEO = "VIDEO"
    VOUCHER = "VOUCHER"

    def __str__(self) -> str:
        return str(self.value)
